default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: book_collection_2_anjalivarghese221_development

test:
  <<: *default
  database: book_collection_2_anjalivarghese221_test

production:
  <<: *default
  database: book_collection_2_anjalivarghese221_production
  username: book_collection_2_anjalivarghese221
  password: <%= ENV["BOOK_COLLECTION_2_ANJALIVARGHESE221_DATABASE_PASSWORD"] %>
