default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: 127.0.0.1
  username: postgres
  password: postgres
  database: book_collection_2_anjalivarghese221_development

test:
  <<: *default
  host: 127.0.0.1
  username: postgres
  password: postgres
  database: book_collection_2_anjalivarghese221_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  
review:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

staging:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
